### PR TITLE
Store match_info in read, in preparation for moving I/O out of AdapterCutter

### PR DESCRIPTION
**Pull request by jdidion**
* Moved code to create match info tuple to Match.get_info_record() (with test)
* In AdapterCutter.__call__, read.match_info is set by calling Match.get_info_record()
* In AdatperCutter._write_info, match info is retrieved from read.match_info

### CODE REVIEW

**Comment by marcelm** [comment]
Hi, just wanted to let you know that I haven’t had time to look at this. Hope you can wait one or two more days.

**Comment by jdidion** [comment]
Sure, no problem

**Comment by marcelm** [comment]
Thanks, this looks good. There are some trailing spaces and I don’t like method names that start with `get_` very much, but that can be fixed later.

**Comment by jdidion** [comment]
Ok, I’ll keep that in mind. Next pull request will be coming shortly. Thanks

**Pull request merged**
